---
- name: Import join command
  ansible.builtin.copy:
    src: join-command
    dest: /tmp/join-command.sh
    mode: '0777'

- name: Join node
  ansible.builtin.command: "sh /tmp/join-command.sh"
  become: true