---
- name: Disable swap (1/2)
  ansible.builtin.command: "swapoff -a"
  become: true

- name: Disable swap (2/2)
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: 'swap'
    replace: '# &'
  become: true

- name: Load overlay and br_netfilter
  ansible.builtin.command: "{{ item }}"
  loop:
    - modprobe overlay
    - modprobe br_netfilter
  become: true

- name: Touch /etc/modules-load.d/k8s.conf
  ansible.builtin.file:
    path: /etc/modules-load.d/k8s.conf
    state: touch
  become: true

- name: Set /etc/modules-load.d/k8s.conf
  ansible.builtin.blockinfile:
    path: /etc/modules-load.d/k8s.conf
    block: |
      overlay
      br_netfilter
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
  become: true

- name: Touch /etc/sysctl.d/k8s.conf
  ansible.builtin.file:
    path: /etc/sysctl.d/k8s.conf
    state: touch
  become: true

- name: Set /etc/sysctl.d/k8s.conf
  ansible.builtin.blockinfile:
    path: /etc/sysctl.d/k8s.conf
    block: |
      net.bridge.bridge-nf-call-iptables = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward = 1
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
  become: true

- name: Apply sysctl changes
  ansible.builtin.command: sysctl --system
  become: true

- name: Install CRI
  ansible.builtin.apt:
    name: containerd
    update_cache: yes
  become: true

- name: Install additional packages
  ansible.builtin.apt:
    name:
      - curl
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg
    update_cache: yes
  become: true

- name: Add k8s key
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
  become: true

- name: Add k8s repository
  ansible.builtin.apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
  become: true

- name: Install k8s packages
  ansible.builtin.apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    update_cache: yes
  become: true

- name: Hold k8s packages
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl
  become: true