---
- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ dns_name }}"
  become: true

- name: Update /etc/hosts
  ansible.builtin.blockinfile:
    path: /etc/hosts
    block: |
      {% for host in groups['all'] %}
      {{ hostvars[host]['ansible_host'] }} {{ hostvars[host]['dns_name'] }} {{ host }}
      {% endfor %}
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
  become: true

- name: Restart systemd-hostnamed
  ansible.builtin.systemd:
    name: systemd-hostnamed
    state: restarted
  become: true

- name: Disable policy-rc.d
  ansible.builtin.file:
    path: /usr/sbin/policy-rc.d
    state: absent
  become: true